### ISSUE TITLE
Previously unregistered nodes reappear

### ISSUE THREAD

**Issue by NickGoward** [bbc/lrud#19]
**Describe the bug**
When a node has been unregistered, all its children are also unregistered. This appears to be the case, however when a node is added with an identical name, the old node can come back under some circumstances.

**To Reproduce**
```
const nav = new Lrud()

nav.registerNode('root', {
  orientation: 'horizontal'
})
nav.registerNode('node1', {
  orientation: 'vertical',
  parent: 'root'
})
nav.registerNode('container', {
  orientation: 'vertical',
  parent: 'node1'
})
nav.registerNode('item', {
  selectAction: {},
  parent: 'container'
})

nav.unregisterNode('root')

nav.registerNode('root', {
  orientation: 'horizontal'
})
nav.registerNode('node2', {
  orientation: 'vertical',
  parent: 'root'
})
nav.registerNode('container', {
  orientation: 'vertical',
  parent: 'node2'
})
nav.registerNode('item', {
  selectAction: {},
  parent: 'container'
})

console.log(nav)
```

**Expected behavior**
It should give a tree of structure:
```
root
-node2
--container
---item
```

It actually gives a tree of structure:
```
root
-node1
--container
---item
-node2
--container
```
So it seems `node1` has returned and `item` is in the`container` under `node1` when it should be in the`container` under `node2`

**Comment by thomascgray** [comment]
Thanks for raising this @NickGoward ! I can indeed replicate the issue, so will do some investigation and get a PR made.
