### ISSUE TITLE
on('select') listener does not fire unless node has its own onSelect method

### ISSUE THREAD

**Issue by NickGoward** [bbc/lrud#27]
**Describe the bug**
If I just want the same select function to fire, I would just set up a `nav.on('select')` listener. But this does not seem to work unless a node also has its own onSelect method.

**To Reproduce**
```
const nav = new Lrud()

nav.on('select', node => console.log(node.selectAction.route))

nav.registerNode('root', {
  orientation: 'vertical'
})

nav.register('item1', {
  parent: 'root',
  selectAction: {
    route: '/home'
  }
})

nav.assignFocus('root')

nav.handleKeyEvent({ direction: 'enter' })
```

**Expected behavior**
I would expect to see my route logged in the console. But I don't... unless I add an onSelect method like this:

```
const nav = new Lrud()

nav.on('select', node => console.log(node.selectAction.route))

nav.registerNode('root', {
  orientation: 'vertical'
})

nav.register('item1', {
  parent: 'root',
  selectAction: {
    route: '/home'
  },
  onSelect: () => {}
})

nav.assignFocus('root')

nav.handleKeyEvent({ direction: 'enter' })
```

**Comment by thomascgray** [comment]
Thanks for raising to our attention! And cheers for raising the issue with reproducible test scenarios 👍 Unfortunately, we don't have capacity to tackle this at the minute. Feel free to raise a PR though? if you wanna do a PR, one of us (LH 🐴 ) can definitely spare some time to go over stuff or whatever
