### ISSUE TITLE
currentFocusNode is horizontal but left/right aren't firing :-/

### ISSUE THREAD

**Issue by jfrux** [bbc/lrud#28]
The up/down events fire but left/right aren't firing for me.
Is there a limitation with how nested nodes can be?

UPDATE: I thought it had to do with the fact that parent was horizontal and isFocusable as well as the children, but when I turn off isFocusable for the parent it throws `Uncaught TypeError: Cannot read property 'id' of undefined`

**Comment by jfrux** [comment]
My problem is that I need to focus a vertical, and in turn focus one of it's children... allowing for horizontal and vertical movement?

Vertical changes categories carousel,
horizontal changes videos in carousel...

But for some reason I cannot seem to get it working...

Had this working with 2.7.x if I recall.

**Comment by jfrux** [comment]
Apparently I've figured it out... I think it just needed to "click" in my brain... thanks and sorry for so many messages.

**Comment by thomascgray** [comment]
Hey @jfrux , apologies for the late reply!

Don't worry about lots of messages! Always better to talk it out.

Glad you managed to solve your problem - is there anywhere you think we can improve the docs, in order to make it easier to "click" in someones head?

LRUD is complicated and solves a very complicated problem, so any suggestions on how to improve docs is welcome!

**Comment by jfrux** [comment]
@thomascgray Thanks for being so kind! I'm not sure yet on the docs... I think people like me are coming here from an "OTT" / "VOD" web app codebase and seeking examples of how to use it with fairly standard TV interfaces.

I think your docs are fine for most, it's definitely a complicated problem to solve and it's doing great at that for sure.  Thanks for continuing to maintain LRUD and all at BBC for what they've done for TV app community.

**Comment by thomascgray** [comment]
Thanks for your kind words @jfrux ! We're always looking to improve our docs, so this is something we'll keep in mind when we're next doing docs work 👍
