### ISSUE TITLE
reindexChildrenOfNode doesn't seem to work right > 9 items...

### ISSUE THREAD

**Issue by jfrux** [bbc/lrud#34]
```javascript
[
0: 0,
1: 1,
2: 10,
3: 11,
4: 12,
5: 13,
6: 14,
7: 15,
8: 16,
9: 17,
10: 18,
11: 19,
12: 2,
13: 20,
14: 21,
15: 22,
16: 23,
17: 24,
18: 3,
19: 4,
20: 5,
21: 6,
22: 7,
23: 8,
24: 9,
]
```

Which is why wrapping isn't working above 9 items... and why  getNodeLastChild() is returning only (at most 9 for me).

Relates to #29 

Let me know if I'm just being silly here... 💯

**Comment by jfrux** [comment]
Wow, actually... just discovered it was the `dist/index.min.js` that wasn't sorting properly...
Somehow with the `dist/index.js` its working.

**Comment by jfrux** [comment]
I take this back... this is still very much a bug.
It MAY be an issue with certain browsers or something...

My app is deployed in FireTV and I put some console logs inside of `Lrud.getNodeLastChild()` and it looks like this... I did a fresh build after adding console.logs to the index.ts's getNodeLastChild(); like so...

```typescript
getNodeLastChild(node: Node): Node {
    console.log("getNodeLastChild()");
    if (!node.children) {
      return undefined
    }
    console.log("node.children before sorting",JSON.parse(JSON.stringify(node.children)));
    const orderedIndexes = Object.keys(node.children).map((childId) => {
      const childIndex = node.children[childId].index;
      console.log(`Mapping child ${childId} to ${childIndex}`);
      return childIndex;
    }).sort();
    console.log("orderedIndexes after sorting",JSON.parse(JSON.stringify(orderedIndexes)));
    console.log("lastIndex of orderedIndex:",orderedIndexes.length - 1);
    return _findChildWithIndex(node, orderedIndexes[orderedIndexes.length - 1])
  }
```
![image](https://user-images.githubusercontent.com/171077/68046282-e9986380-fcb1-11e9-9c3d-f51b8c629451.png)

So what's happening is... since the last index returns 9... the wrapping nature of the response is always 9.

**Comment by jfrux** [comment]
```js
const orderedIndexes = Object.keys(node.children).map(childId => node.children[childId].index).sort()
```
to
```js
const orderedIndexes = Object.keys(node.children).map(childId => node.children[childId].index)
```

Fixes the problem.

**Comment by epatrasc** [comment]
> ```js
> sort()
> ```

Hi @jfrux ,

Thanks for your investigation, you're right. The `sort`, without a proper callback, is not sorting the indexes properly, it's treating number as string.

I'll open a PR to fix the issue.
