### ISSUE TITLE
Using setActiveChild on an element with a parent that isn't currently focused de-syncs activeChild and currentFocusNode

### ISSUE THREAD

**Issue by edmorrish** [bbc/lrud#40]
**Describe the bug**
When setActiveChild is called on an element that's a leaf with a parent that's not the activeChild of its own parent the activeChild of the parent of a focused element can change, leading to navigation problems.

**To Reproduce**
Test case

```js
const navigation = new Lrud()
navigation
        .registerNode('root')
        .registerNode('a', { parent: 'root' })
        .registerNode('b', { parent: 'root' })
        .registerNode('a0', { isFocusable: true, parent: 'a' })
        .registerNode('b0', { isFocusable: true, parent: 'b' })

      navigation.assignFocus('b0')
      navigation.setActiveChild('a', 'a0')
      expect(navigation.currentFocusNodeId).toEqual('b0')
      expect(navigation.getNode('root').activeChild).toEqual('b')

```
First expect passes indicating focus hasn't changed, second expect fails, so the focused element is no longer in the path of active children.

**Expected behavior**
setActiveChild should probably not bubble upwards, or maybe should have an option to disable bubbling, the current behaviour can cause problems when changing the activeChild on a different section of the tree.

**Comment by edmorrish** [comment]
I guess really setActiveChild should be checking for whether the currentFocusNode is a parent of the parent before re-assigning its activeChild. Unless there's a case where we want a parent to have a focused child and an active child and have those two be different, but that seems very wrong.

**Comment by jordanholt** [comment]
Agreed, we don't want to allow a situation where a sub-tree can have different `focus` and `activeChild` nodes on the same level.

**Comment by edmorrish** [comment]
I'm going to jump on this if nobody's started.

**Comment by jordanholt** [comment]
Sure!

**Comment by edmorrish** [comment]
Hmm. I really can't get my head around why this would ever need to bubble upwards but removing it breaks a lot of stuff. It seems like really unexpected behaviour for `setActiveChild` to set the activeChild of its parents, but 19 tests rely on it doing that apparently.

**Comment by jordanholt** [comment]
Or can we just make it figure out the point at which the trees converge (if they do) and only setting the `activeChild` property on nodes up to that point?

**Comment by edmorrish** [comment]
Implementation of the major bump change is done: https://github.com/bbc/lrud/compare/shallow-setactive, going to hold off on a PR until I've tried a bit more stuff in case there's any other API breaking changes we might want to make.

**Comment by jordanholt** [comment]
@bbc/lovely-horse what are your thoughts on this?
* What should the default behaviour of `setActiveChild` be?
* Should it recurse up the tree but only up to the point that it converges with the sub-tree that has the current focus?
* Should we outright change the behaviour to not recurse (see implementation in #44)?
* Should this just be more explicit opt-in via a flag that's passed to `setActiveChild`?

**Comment by jordanholt** [comment]
After the discussion, we agree that `setActiveChild()` should not recurse. The current behaviour of that function should be moved into another function `setActiveChildRecursive()` (or similar name).

Additionally, the `assignFocus()` function should be updated to use the recursive function to retain that behaviour.

Function name changes would still mean a breaking change, but that's okay.

**Comment by edmorrish** [comment]
Have re-implemented the current behaviour in `setActiveChildRecursive` here: https://github.com/bbc/lrud/pull/44/files
