### ISSUE TITLE
Can set a node's activeChild to be a non-focusable element

### ISSUE THREAD

**Issue by edmorrish** [bbc/lrud#41]
**Describe the bug**
It is possible to set a non-focusable node to be the activeChild of a parentElement, this can cause problems changing focus when a different child of that parentElement is focused.

**To Reproduce**
```js
      const navigation = new Lrud()
      navigation
        .registerNode('root')
        .registerNode('parent', { orientation: 'vertical' })
        .registerNode('a', { parent: 'parent' })
        .registerNode('b', { parent: 'parent', isFocusable: true })

      navigation.assignFocus('b')
      navigation.handleKeyEvent({ direction: 'UP' })
      expect(navigation.currentFocusNodeId).toEqual('b')
      expect(navigation.getNode('parent').activeChild).toEqual('b')  // Fails: activeChild is 'a'
```
**Expected behavior**
In this test case parent's activeChild should still be 'b', 'a' has never been focusable so can't be active.

**Comment by edmorrish** [comment]
Cause of this is https://github.com/bbc/lrud/blob/master/src/index.ts#L490.
Possible solution is to check that the child is focusable before assigning the activeChild.

**Comment by jordanholt** [comment]
If the child was focusable it should've just returned it at the top of `digDown` [here](https://github.com/bbc/lrud/blob/master/src/index.ts#L435). 

It looks like that block is just using the `activeChild` as a cursor when looking for the next child, which doesn't seem right... 🤔

**Comment by edmorrish** [comment]
I can't think of a good reason why digDown should be mutating the tree at all really, maybe we could remove the use of activeChild to get the next child and just store that as a variable instead.

**Comment by edmorrish** [comment]
digDown changes the parent node's activeChild in order to index through sibling trees, could probably be replaced either by sending a modified node to `getNextChildInDirection` or maybe adding some options to those functions to specify the current activeChild.
