### ISSUE TITLE
Default key codes and matching devices

### ISSUE THREAD

**Issue by MaxMilton** [bbc/lrud#7]
I've been looking into the default set of key codes provided in `lrud` and I can't figure some of them out. My approach has been to search the [tal repo](https://github.com/bbc/tal/tree/master/config/devices) device configs to find matching devices.

The following don't match any device:

```js
218: left,
217: right,
215: up,
216: down,
```

Even googling them I couldn't find anything useful. **What device/s are they intended for?**

Similarly, the following key codes are only used on Universal Windows Platform (UWP):

```js
214: left,
205: left,
213: right,
206: right,
211: up,
203: up,
212: down,
204: down,
195: enter,
```

Is it worth including key code definitions only used on a single platform by default? Or maybe do they also apply to some other platform/s? Of course, it does no harm to include them but I'm just curious about what the reasoning is behind including them :slightly_smiling_face:

**Comment by thomascgray** [comment]
Unfortunately, the original developers of LRUD are no longer around to ask, so I can't answer for the reasoning on all the key codes.

I *do* know that LRUD is used on a bunch of different devices, and so the key code definitions are kinda of something we inherited and just running with until we face any problems.

**Comment by MaxMilton** [comment]
No prob, thanks for the reply.

For anyone finding this later, this is the commit on the original project which added the key codes (doesn't doesn't shed any more light onto which devices they map to sadly): https://github.com/stuart-williams/lrud/commit/97dcd8ee67fd00ea077c74c0803971e2ef408c5f
