### ISSUE TITLE
Unregistering root node causes error

### ISSUE THREAD

**Issue by codan84** [bbc/lrud#8]
To replicate:
```
const { Lrud } = require('lrud')

const navigation = new Lrud()

navigation.registerNode('root', { orientation: 'vertical' })
navigation.unregisterNode('root') // => ERROR: Cannot read property 'children' of undefined
```

**Problem**: Lrud assumes that there's always a parent node of the node we want to unregister. This is an incorrect assumption, preventing us from unregistering a root node.

Problematic line that throws an error: https://github.com/bbc/lrud/blob/master/src/index.ts#L222

**Comment by thomascgray** [comment]
@codan84 thanks for finding & raising an issue! We didn't look into unregistering without a parent, as we've not needed a reason to unregister the root node.

However, this is a valid use case, so will get a PR up and link it in here when complete.
