### ISSUE TITLE
Registering a root node if one already exists

### ISSUE THREAD

**Issue by codan84** [bbc/lrud#9]
To replicate:
```
const { Lrud } = require('lrud')

const navigation = new Lrud()

navigation.registerNode('root', { orientation: 'vertical' })
navigation.registerNode('root', { orientation: 'horizontal' })

console.log(navigation.tree)
```
**Problem**: trying to register a root node _again_ (with the same id, orientation etc doesn't matter) does not change the existing root node to the new one. Instead, it _adds_ another node at the root of the navigation tree, except the node is added with an `undefined` id.  
  
**Expected behaviour**: either throw an error to say this node already exists (make it explicit that we can't do it), or unregister existing root node (see other issue I submitted!) and register new one in it's place.

**Comment by thomascgray** [comment]
@codan84 thanks again for finding & raising! After a bit of an internal discussion, we also agree LRUD should throw an exception in this instance. Getting a fix out now.
