### ISSUE TITLE
Should I use insertTree or registerTree?

### ISSUE THREAD

**Issue by EwanRoycroft** [bbc/lrud#94]
In usage.md, there is a section named [`insertTree()`](https://github.com/bbc/lrud/blob/master/docs/usage.md#inserttree-and-nested-tree-registration), but all of the example code uses `instance.registerTree()`. Is this a typo? Which one should I use?

**Comment by ben-whitfield** [comment]
Hi Ewan, iirc we use `registerTree()` for the initial registering of a whole tree, the `insertTree()` is when we are attempting to register new nodes to the existing tree.

**Comment by EwanRoycroft** [comment]
Great, thanks.
